// <auto-generated />
using ClubSystemsTest.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClubSystemsDemo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ClubSystemsTest.Models.MembershipDetails", b =>
                {
                    b.Property<int>("MemebershipID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MemebershipID"), 1L, 1);

                    b.Property<decimal>("AccountBalance")
                        .HasColumnType("money");

                    b.Property<int>("PersonID")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MemebershipID");

                    b.HasIndex("PersonID");

                    b.HasIndex("Type", "PersonID")
                        .IsUnique();

                    b.ToTable("MembershipDetails");

                    b.HasData(
                        new
                        {
                            MemebershipID = 1,
                            AccountBalance = 10m,
                            PersonID = 1,
                            Type = "Primary"
                        },
                        new
                        {
                            MemebershipID = 2,
                            AccountBalance = 10m,
                            PersonID = 1,
                            Type = "Secondary"
                        },
                        new
                        {
                            MemebershipID = 3,
                            AccountBalance = -15m,
                            PersonID = 2,
                            Type = "Primary"
                        },
                        new
                        {
                            MemebershipID = 4,
                            AccountBalance = -5m,
                            PersonID = 3,
                            Type = "Basic"
                        });
                });

            modelBuilder.Entity("ClubSystemsTest.Models.UserDetails", b =>
                {
                    b.Property<int>("PersonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonID"), 1L, 1);

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Forename")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("PersonID");

                    b.ToTable("UserDetails");

                    b.HasData(
                        new
                        {
                            PersonID = 1,
                            EmailAddress = "Carson.Alexander@gmail.com",
                            Forename = "Carson",
                            Surname = "Alexander"
                        },
                        new
                        {
                            PersonID = 2,
                            EmailAddress = "Carson.Alexander@hotmail.com",
                            Forename = "Carson",
                            Surname = "Alexander2"
                        },
                        new
                        {
                            PersonID = 3,
                            EmailAddress = "Ajay.Peddapala@hotmail.com",
                            Forename = "Ajay",
                            Surname = "Peddapala"
                        });
                });

            modelBuilder.Entity("ClubSystemsTest.Models.MembershipDetails", b =>
                {
                    b.HasOne("ClubSystemsTest.Models.UserDetails", "UserDetails")
                        .WithMany("Memberships")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserDetails");
                });

            modelBuilder.Entity("ClubSystemsTest.Models.UserDetails", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
